app/web/employees/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'employees'

urlpatterns = [
    path('', index, name='index'),

    path('tree/', employee_tree, name='tree'),
    path('list/', employee_list, name='list'),

    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='employees/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='employees/logged_out.html'), name='logout'),

    path('add/', create_employee, name='create_employee'),
    path('delete/', delete_employee, name='delete_employee'),
    path('update/', update_employee, name='update_employee'),
]

app/web/web/urls.py
from django.contrib import admin
from employees.views import *
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls', namespace='employees')),
]

app/web/employees/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey



class Employee(MPTTModel):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=20)
    email = models.EmailField()
    employment_date = models.DateField()
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')


    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']
        max_level = 7

app/web/employees/views.py
from django.contrib.auth.forms import UserCreationForm
from .form import EmployeeForm
from .models import Employee
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm


def index(request):
    return render(request, 'employees/index.html')

def employee_tree(request):
    nodes = Employee.objects.all()
    return render(request, 'employees/employee.html', {'nodes': nodes})


def employee_list(request):
    employees = Employee.objects.all()

    # get value for sorting
    sort_by = request.GET.get('sort', 'name')

    # filter
    query = request.GET.get('q')
    if query:
        employees = employees.filter(
            Q(name__icontains=query) | Q(position__icontains=query) | Q(email__icontains=query))

    # sort
    if sort_by in ['name', 'position', 'email', 'employment_date']:
        employees = employees.order_by(sort_by)

    context = {
        'employees': employees,
        'sort_by': sort_by,
        'query': query,
    }
    return render(request, 'employees/employee_list.html', context)


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('/')
        else:
            print(form.errors)
    else:
        form = UserCreationForm()
    return render(request, 'employees/register.html', {'form': form})



def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                form.add_error(None, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    return render(request, 'employees/login.html', {'form': form})

@login_required
def logout_view(request):
    logout(request)
    return redirect('/index/')




@login_required
def profile(request):
    user = request.user
    context = {'user': user}
    return render(request, 'employees/profile.html', context)

from django.contrib.auth.decorators import login_required

@login_required
def create_employee(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('employees:list')
    else:
        form = EmployeeForm()

    context = {'form': form}
    return render(request, 'employees/create_employee.html', context)


@login_required
def delete_employee(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        employee = get_object_or_404(Employee, name=name)
        employee.delete()
        return redirect('employees:list')

    return render(request, 'employees/delete_employee.html')


@login_required
def update_employee(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        employee = get_object_or_404(Employee, name=name)

        employee.name = request.POST.get('new_name', employee.name)
        employee.position = request.POST.get('new_position', employee.position)
        employee.email = request.POST.get('new_email', employee.email)
        employee.employment_date = request.POST.get('new_employment_date', employee.employment_date)
        employee.save()

        return redirect('employees:list')

    return render(request, 'employees/update_employee.html')

app/web/employees/templates/employees/create_employee.html
<!DOCTYPE html>
<html>
  <head>
    <title>Create Employee</title>
  </head>
  <body>
    <h1>Create Employee</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
    </form>
  </body>
</html>

app/web/employees/templates/employees/delete_employee.html
<!DOCTYPE html>
<html>
  <head>
    <title>Delete Employee</title>
  </head>
  <body>
    <h1>Delete Employee</h1>
    <form method="post">
      {% csrf_token %}
      <div>
        <label for="name">Employee name:</label>
        <input type="text" id="name" name="name">
      </div>
      <button type="submit">Delete</button>
    </form>
  </body>
</html>

app/web/employees/templates/employees/employee.html
<!DOCTYPE html>
<html>
<head>
    <title>Employees hierarchy</title>
    <button onclick="location.href='{% url 'employees:index' %}'">Go to homepage</button>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
</head>
<body>
{% load mptt_tags %}

<!-- Добавляем классы "container" и "my-5" для создания контейнера с отступами -->
<div class="container my-5">
    <!-- Добавляем классы "list-group" и "list-group-flush" для создания списка без рамок и отступов -->
    <ul class="list-group list-group-flush">
        {% recursetree nodes %}
            <!-- Добавляем класс "list-group-item" для создания элементов списка -->
            <li class="list-group-item">
                Name - {{ node.name }},  (Position - {{ node.position }})
                <br>
                {% if node.children %}
                    <!-- Добавляем класс "list-group" для создания вложенного списка -->
                    <ul class="list-group">
                        {{ children }}
                    </ul>
                {% endif %}
            </li>
        {% endrecursetree %}
    </ul>
</div>

app/web/employees/templates/employees/employee_list.html
<!DOCTYPE html>
<html>
  <head>
    <title>Employee List</title>
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }

      td, th {
        padding: 8px;
        text-align: left;
      }

      tr:nth-child(even) {
        background-color: #f2f2f2;
      }

      .button-container {
        text-align: right;

      }
      h1 {
        text-align: center;
        display: centre;
      }

      .button-container button {
        margin-left: 30px;
      }
    </style>
  </head>
  <body>
    {% block content %}
    <div class="container">
      <h1>Employee list</h1>
      {% if user.is_authenticated %}
        <div class="button-container">
          <button onclick="location.href='{% url 'employees:create_employee' %}'">Create</button>
          <button onclick="location.href='{% url 'employees:update_employee' %}'">Update</button>
          <button onclick="location.href='{% url 'employees:delete_employee' %}'">Delete</button>
          <button onclick="location.href='{% url 'employees:index' %}'">Go to homepage</button>
        </div>
      {% endif %}

      <form method="get">
        <div class="form-group">
          <label for="search">Search:</label>
          <input type="text" class="form-control" id="search" name="q" value="{{ query }}">
        </div>

        <div class="form-group">
          <label for="sort">Sort by:</label>
          <select class="form-control" id="sort" name="sort">
            <option value="name" {% if sort_by == "name" %}selected{% endif %}>Name</option>
            <option value="position" {% if sort_by == "position" %}selected{% endif %}>Position</option>
            <option value="email" {% if sort_by == "email" %}selected{% endif %}>Email</option>
            <option value="employment_date" {% if sort_by == "employment_date" %}selected{% endif %}>Employment Date</option>
          </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>

      </form>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Email</th>
            <th>Employment Date</th>
          </tr>
        </thead>
        <tbody>
          {% for employee in employees %}
          <tr>
            <td>{{ employee.name }}</td>
            <td>{{ employee.position }}</td>
            <td>{{ employee.email }}</td>
            <td>{{ employee.employment_date }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endblock %}
  </body>
</html>

app/web/employees/templates/employees/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        .btn {
            display: inline-block;
            padding: 0.5rem 1rem;
            background-color: gray;
            color: #fff;
            text-decoration: none;
            font-size: 18px;
            border-radius: 5px;
        }
    </style>
    <title>Hierarchy employees</title>
</head>
<body>
    <h1>Hierarchy employees</h1>
    <div>
        <a href="{% url 'employees:register' %}" class="btn">Registration</a>
        <a href="{% url 'employees:tree' %}" class="btn">Part 1</a>
        <a href="{% url 'employees:list' %}" class="btn">Part 2</a>
        <a href="{% url 'employees:login' %}" class="btn">login</a>
        <a href="{% url 'employees:logout' %}" class="btn">logout</a>
        {% if user.is_authenticated %}
             <a href="{% url 'employees:profile' %}" class="btn">My profile</a>
        {% endif %}
    </div>
</body>
</html>

app/web/employees/templates/employees/login.html
{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enter</button>
    </form>
    <button onclick="location.href='{% url 'employees:index' %}'">Go to homepage</button>
{% endblock %}

app/web/employees/templates/employees/profile.html
<!DOCTYPE html>
<html>
<head>
	<title>Profile Page</title>
</head>
<body>
	<h1>Welcome to your profile page, {{ user.username }}!</h1>
	<button onclick="location.href='{% url 'employees:index' %}'">Go to homepage</button>
</body>
</html>

app/web/employees/templates/employees/register.html
{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
    <button onclick="location.href='{% url 'employees:index' %}'">Go to homepage</button>
  </form>
  {% if form.errors %}
    <p>Errors:</p>
    <ul>
    {% for error in form.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

app/web/employees/templates/employees/update_employee.html
<!DOCTYPE html>
<html>
  <head>
    <title>Update Employee</title>
    <style>
      form div {
        display: flex;
        align-items: left;
        margin-bottom: 10px;
      }

      label {
        width: 150px;
        text-align: left;
        margin-right: 10px;
        margin-left: 10px;
      }

      input[type="text"] {
        flex: 1;
        width: 100px;
      }
    </style>
  </head>
  <body>
    <h1>Update Employee</h1>
    <form method="post">
      {% csrf_token %}
      <div>
        <label for="name">Employee name:</label>
        <input type="text" id="name" name="name">
      </div>
      <div>
        <label for="new_name">New name:</label>
        <input type="text" id="new_name" name="new_name">
      </div>
      <div>
        <label for="new_position">New position:</label>
        <input type="text" id="new_position" name="new_position">
      </div>
      <div>
        <label for="new_email">New email:</label>
        <input type="text" id="new_email" name="new_email">
      </div>
      <div>
        <label for="new_employment_date">New employment date:</label>
        <input type="text" id="new_employment_date" name="new_employment_date">
      </div>
      <button type="submit">Update</button>
    </form>
  </body>
</html>